version: '3.8'

services:
  db:
    image: postgres:15
    container_name: real_estate_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    image: php:8.2-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - ACCEPT_EULA=Y
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  db_data: {}
